baseURL = 'https://kusca.dev/'
languageCode = 'tr'
title = 'kusca.dev'
theme = "hugo-theme-console"

[params]
  description = "kusca.dev Yaz覺l覺m/Teknoloji blogu."
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 
  
#  [[params.navlinks]]
#  name = "hakk覺mda/"
#  url = "about/"

  [[params.navlinks]]
  name = "yaz覺lar/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "kategoriler/"
  url = "categories/"

  [[params.navlinks]]
  name = "RSS/"
  url = "https://kusca.dev/rss.xml"



#  [[params.navlinks]]
#  name = "photos/"
#  url = "photos/"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "rss"
